import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { BellRing, CheckCheck, MapPin, Undo2 } from "lucide-react";
import { api } from "@/lib/api";
import { useFetch } from "@/hooks/useFetch";
import { useWorkflow } from "@/context/WorkflowContext";
import { PageHeader, ErrorState } from "@/components/common/PageHeader";
import { StatusChip } from "@/components/common/StatusChip";
import { Button } from "@/components/ui/button";
import { ts } from "@/lib/format";

const SEV = ["ALL", "CRITICAL", "HIGH", "WATCH", "INFORMATION"];

export default function Alerts() {
  const navigate = useNavigate();
  const { setSelectedHabId } = useWorkflow();
  const alerts = useFetch(() => api.alerts(), []);
  const [sev, setSev] = useState("ALL");
  const [showAck, setShowAck] = useState(true);

  const rows = useMemo(() => {
    let list = alerts.data?.alerts || [];
    if (sev !== "ALL") list = list.filter((a) => a.severity === sev);
    if (!showAck) list = list.filter((a) => a.status !== "Acknowledged");
    return list;
  }, [alerts.data, sev, showAck]);

  const ack = async (a) => {
    try {
      await api.acknowledgeAlert(a.id, "Control room officer");
      toast.success(`Acknowledged: ${a.location}`);
      alerts.reload();
    } catch (e) {
      toast.error("Could not acknowledge alert");
    }
  };
  const unack = async (a) => {
    await api.unacknowledgeAlert(a.id);
    alerts.reload();
  };

  const counts = useMemo(() => {
    const c = { CRITICAL: 0, HIGH: 0, WATCH: 0, INFORMATION: 0, open: 0 };
    (alerts.data?.alerts || []).forEach((a) => {
      c[a.severity] += 1;
      if (a.status === "Open") c.open += 1;
    });
    return c;
  }, [alerts.data]);

  return (
    <div className="p-4">
      <PageHeader eyebrow="Alerts" title="Engine-generated alerts" description={alerts.data?.note || "Alerts generated by the prototype's own scoring engine."} actions={<span className="text-xs text-foreground/60"><span className="font-mono font-semibold">{counts.open}</span> open</span>} />

      <div className="mb-3 flex flex-wrap items-center gap-2">
        {SEV.map((s) => (
          <button key={s} onClick={() => setSev(s)} className={`rounded-md border px-2.5 py-1 text-xs transition-colors ${sev === s ? "border-primary/60 bg-primary/15" : "border-border/60 text-foreground/70 hover:bg-white/5"}`} data-testid={`alert-filter-${s.toLowerCase()}`}>
            {s === "ALL" ? "All" : s} {s !== "ALL" && <span className="font-mono text-foreground/50">{counts[s]}</span>}
          </button>
        ))}
        <label className="ml-auto flex items-center gap-2 text-xs text-foreground/70">
          <input type="checkbox" checked={showAck} onChange={(e) => setShowAck(e.target.checked)} className="accent-[hsl(var(--primary))]" data-testid="alerts-show-acknowledged" /> show acknowledged
        </label>
      </div>

      {alerts.error && <ErrorState error={alerts.error} onRetry={alerts.reload} />}
      <div className="panel-surface overflow-x-auto">
        <table className="w-full dense-table" data-testid="alerts-table">
          <thead>
            <tr>
              <th>Severity</th>
              <th>Type</th>
              <th>Location</th>
              <th>Message</th>
              <th>Recommended action</th>
              <th>Timestamp</th>
              <th>Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {rows.map((a) => (
              <tr key={a.id} className={a.status === "Acknowledged" ? "opacity-60" : ""} data-testid={`alert-row-${a.id}`}>
                <td>
                  <StatusChip kind="alert" value={a.severity} testId="alert-severity-chip" />
                </td>
                <td className="text-xs text-foreground/75">{a.type}</td>
                <td>
                  <div className="font-medium text-sm">{a.location}</div>
                  {a.priority_class && <StatusChip kind="priority" value={a.priority_class} className="mt-0.5" />}
                </td>
                <td className="max-w-[320px] text-xs text-foreground/80">{a.message}</td>
                <td className="max-w-[280px] text-xs text-foreground/70">{a.recommended_action}</td>
                <td className="font-mono text-[11px] text-foreground/60">{ts(a.timestamp)}</td>
                <td>
                  <span className={`chip ${a.status === "Open" ? "chip-high" : "chip-safe"}`}>{a.status}</span>
                  {a.acknowledged_at && <div className="font-mono text-[10px] text-foreground/45">{ts(a.acknowledged_at)}</div>}
                </td>
                <td>
                  <div className="flex items-center gap-1">
                    {a.habitation_id && (
                      <button className="rounded-md border border-border/60 p-1.5 hover:bg-white/5" title="Open on map" onClick={() => { setSelectedHabId(a.habitation_id); navigate(`/command-center?hab=${a.habitation_id}`); }} data-testid={`alert-map-${a.id}`}>
                        <MapPin className="h-3.5 w-3.5" />
                      </button>
                    )}
                    {a.status === "Open" ? (
                      <Button size="sm" variant="outline" onClick={() => ack(a)} data-testid="alerts-acknowledge-button">
                        <CheckCheck className="h-3.5 w-3.5" /> Acknowledge
                      </Button>
                    ) : (
                      <Button size="sm" variant="ghost" onClick={() => unack(a)} data-testid="alerts-reopen-button">
                        <Undo2 className="h-3.5 w-3.5" /> Reopen
                      </Button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
            {!alerts.loading && rows.length === 0 && (
              <tr>
                <td colSpan={8} className="!py-8 text-center text-xs text-foreground/50">
                  <BellRing className="mx-auto mb-1 h-4 w-4" /> No alerts for this filter.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
